-- AlterTable
ALTER TABLE "TestCase" ADD COLUMN     "isGCS" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "output" DROP NOT NULL,
ALTER COLUMN "stdin" DROP NOT NULL,
ALTER COLUMN "stdout" DROP NOT NULL;
